language: java
sudo: false
install: true

addons:
   sonarcloud:
      organization: "csc308"
      token:
         secure: "786b8964c8c0a9f2855eaf71fc9e306a9402e0b8"
jdk:
   - oraclejdk8
script: 
   - bash sonar.sh

cache:
   directories:
      - '$HOME/.m2/repository'
      - '$HOME/.sonar/cache'


